---
- name: Install and Configure Nginx
  hosts: all
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: myKey.pem
  become: yes

  tasks:
    - name: Check Python version
      command: python3 --version
      register: python_version

    - debug:
        var: python_version.stdout

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html file
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'